### ISSUE TITLE
Possible bug implying meta is present

### ISSUE THREAD

**Issue by klobuczek** [jsonapi-suite/jsonapi_errorable#14]
I didn't have much time to analyze this, but I think meta should not be mandatory for simple posts of single resource. It leads to error in my case.
https://github.com/jsonapi-suite/jsonapi_errorable/blame/master/lib/jsonapi_errorable/serializers/validation.rb#L136

**Comment by richmolj** [comment]
@klobuczek what's the error? The `meta` this is referencing is something the deserializer class in compliable sets, it is not part of the payload you send to the server.

**Comment by klobuczek** [comment]
@richmolj I think `payload[:meta]` is nil in my case. The error I got was no `[]` method on nil. This does not happen in 0.7.0

**Comment by richmolj** [comment]
@klobuczek could you paste the payload you are sending? I am not sure how that would be the case.

**Comment by klobuczek** [comment]
@richmolj it was a customization problem in our code. Sorry for the false alarm.
