### ISSUE TITLE
Allow to set meta

### ISSUE THREAD

**Issue by BjornMelgaard** [jsonapi-suite/jsonapi_errorable#3]
```
  register_exception StrongerParameters::InvalidParameter,
                     code:    :unprocessable_entity,
                     title: 'Validation Error',
                     status:  422,
                     message: ->(e) { e.message },
                     meta: ->(e) { { value: e.value, key: e.key } }
```

Output 
```
{"errors"=>                                                                                                           |  ETA: ??:??:??
  [{"code"=>"unprocessable_entity",
    "status"=>"422",
    "title"=>"Validation Error",
    "detail"=>"Invalid parameter: name must be a string",
    "meta"=>{}}]}
```

Also it would be nice to have predefined exception handler for StrongerParameters::InvalidParameter

**Comment by richmolj** [comment]
See the "custom exception handler" section of https://jsonapi-suite.github.io/jsonapi_errorable. You can override `meta` in your exception class. That said, not against a PR allowing this as an option to `register_exception` as well.

I agree we should have a predefined handler for `StrongerParameters::InvalidParameter`, though I think we need something in the response differentiating a validation error and an invalid parameter error. I'll get to this at some point, or maybe submit a PR?

**Comment by BjornMelgaard** [comment]
Maybe someday, for now I can not decide what to choose: jsonapi-suite or jsonapi-resources
For example, can I use jsonapi_swagger_helpers already?

**Comment by richmolj** [comment]
I removed support for swagger helpers because we supported so many query parameters "out of the box" the default swagger UI was unusable. We're working on an alternative (either an alternative UI or something else altogether).

FWIW, this library was created as a more Rails-y alternative to JR. It's more powerful, as it supports querying and saving nested resources. and has better support for non-AR use cases IMO. There are other reasons, like support for statistics and `extra_fields`, but those are the main ones. I'd recommend the [tutorial](https://gist.github.com/richmolj/c7f1adca75f614bb71b27f259ff3c37a) and compare it with your JR experience. Definitely willing to support what people need, auto-documentation is next on the list.

**Comment by BjornMelgaard** [comment]
Yes, the project is awesome and I believe that someday it will be as popular as `jsonapi-resources`, but the problem as old as time: be on my own or not :) Will see

**Comment by BjornMelgaard** [comment]
P.S. because of the way stronger_parameters work (raise on log when stumbles upon invalid parameter) its impossible to assemble all errors and pass to `render_errors` in bundle
Will try to make friends of rectify and jsonapi-suite (perhaps)

**Comment by richmolj** [comment]
Are you saying you want to combine model validation errors and strong_params errors? I think it is correct that these are separate error responses with a different status code, though I agree stronger_param errors should be jsonapi compliant.

**Comment by BjornMelgaard** [comment]
> Are you saying you want to combine model validation errors and strong_params errors? 

no, substitute strong_params with something like Rectify form objects. Unlike strong params it will assemble errors like model validations, but they are conditional per actions

```ruby
class AttachmentsController < ApplicationController
  before_action :authenticate_user!
  jsonapi resource: AttachmentResource
  jsonapi_form :attachment_that_allow_nestings, only: :create
  jsonapi_form :attachment, only: :update
  ....
end

# app/forms/...
class AttachmentThatAllowNestingsForm < JsonapiForm
  mimic Attachment # import validations from model
  attribute :file, File
  attribute :id, String # so, unlike stronger_params, if id was integer - coerce

  has_many :nestings, Array[Nesting]

  validates :file, :id, :presence => true
  validate :custom_valid

  def custom_valid
     ...
   end
end
```

That what I first thought, but now I think that I can get along with strong_resources, it has all things, and coercion I can make like this

```ruby
# config/initializers/strong_resources.rb
strong_resource :person do
  attribute :id, :integer_or_string # to allow json id: 1 or id: '1', so rails model will coerce it for us anyway
end
```
do not pay attention, just thinking out loud )

I've [joined pundit and jsonapi](http://sg.blobla.com/content2/megames/ppap/intro.jpg) (in progress), [take a look](https://github.com/BjornMelgaard/ngrx-todolist/blob/with_jsonapi_suite/app/resources/concerns/pundit_resource.rb) )
