### ISSUE TITLE
Undefined local variable or method `deserialized_params'

### ISSUE THREAD

**Issue by stas** [jsonapi-suite/jsonapi_errorable#5]
After 4eb7951b4851170e0a948781dcc029f4bc7d530e the `#render_errors_for` no longer works.

Please take a look.

**Comment by richmolj** [comment]
Hi @stas upgrade to the latest version of jsonapi_suite and it should work. Please bear with us while we solidify things for 1.0

**Comment by stas** [comment]
Actually, I'm using this package standalone. I tried to understand why this dependency was introduced and went back keeping the v0.1.1 instead.

Feel free to close the ticket if you think it's not relevant anymore.

**Comment by mattruzicka** [comment]
I'm also seeing this error. How is `deserialized_params` suppose to be defined?
